// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SBN_Application.Data;

#nullable disable

namespace SBN_Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031103826_AddTotalDiterimaFieldToAssets")]
    partial class AddTotalDiterimaFieldToAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SBN_Application.Models.Asset", b =>
                {
                    b.Property<int>("Id_Asset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Asset"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Buyer")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Sbn")
                        .HasColumnType("integer");

                    b.Property<int>("Modal")
                        .HasColumnType("integer");

                    b.Property<int>("Tenor")
                        .HasColumnType("integer");

                    b.Property<double>("Total_Diterima")
                        .HasColumnType("double precision");

                    b.HasKey("Id_Asset");

                    b.HasIndex("Id_Buyer");

                    b.HasIndex("Id_Sbn");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SBN_Application.Models.Buyer", b =>
                {
                    b.Property<int>("Id_Buyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Buyer"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama_Buyer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Rek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Telp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Buyer");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("SBN_Application.Models.SBN", b =>
                {
                    b.Property<int>("Id_Sbn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Sbn"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Fixed_Rate")
                        .HasColumnType("double precision");

                    b.Property<string>("Kode_Sbn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Min_Beli")
                        .HasColumnType("integer");

                    b.Property<string>("Nama_Sbn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipe_Investor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Sbn");

                    b.ToTable("SBNs");
                });

            modelBuilder.Entity("SBN_Application.Models.Asset", b =>
                {
                    b.HasOne("SBN_Application.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("Id_Buyer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SBN_Application.Models.SBN", "Sbn")
                        .WithMany()
                        .HasForeignKey("Id_Sbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Sbn");
                });
#pragma warning restore 612, 618
        }
    }
}
